### ISSUE TITLE
ceph osd 安装过程中，分区失败导致ceph osd未能正常启动。

### ISSUE THREAD

**Issue by jiamliang** [k8sp/sextant#317]
现象：在其中的一台GPU服务器上（多个硬盘）安装ceph osd的时候，docker container一直处于 restart 的状态：
``` shell
core@0c-c4-7a-82-c5-bc ~ $ docker ps -a | grep ceph
fcb289cdf4f5        bootstrapper:5000/typhoon1986/ceph-daemon:tag-build-master-jewel-ubuntu-14.04-fix370   "/bin/bash -x /entryp"   About an hour ago   Restarting (1) 22 seconds ago                       ceph_osd_sdd
445d6801251d        bootstrapper:5000/typhoon1986/ceph-daemon:tag-build-master-jewel-ubuntu-14.04-fix370   "/bin/bash -x /entryp"   About an hour ago   Up About an hour                                    ceph_osd_sdc
8a1d5576afea        bootstrapper:5000/typhoon1986/ceph-daemon:tag-build-master-jewel-ubuntu-14.04-fix370   "/bin/bash -x /entryp"   About an hour ago   Up About an hour                                    ceph_osd_sdb
ca9969955b25        bootstrapper:5000/typhoon1986/ceph-daemon:tag-build-master-jewel-ubuntu-14.04-fix370   "/entrypoint.sh mds"     About an hour ago   Up About an hour                                    ceph_mds
b20a315a1c29        bootstrapper:5000/typhoon1986/ceph-daemon:tag-build-master-jewel-ubuntu-14.04-fix370   "/entrypoint.sh mon"     About an hour ago   Up About an hour                                    ceph_mon
```

查看硬盘分区情况：
``` shell
core@0c-c4-7a-82-c5-bc ~ $ lsblk
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda      8:0    0 119.2G  0 disk 
|-sda1   8:1    0   128M  0 part /boot
|-sda2   8:2    0     2M  0 part 
|-sda3   8:3    0     1G  0 part /usr
|-sda4   8:4    0     1G  0 part 
|-sda6   8:6    0   128M  0 part /usr/share/oem
|-sda7   8:7    0    64M  0 part 
`-sda9   8:9    0 116.9G  0 part /
sdb      8:16   0   1.8T  0 disk 
|-sdb1   8:17   0   1.8T  0 part 
`-sdb2   8:18   0   100M  0 part 
sdc      8:32   0   1.8T  0 disk 
|-sdc1   8:33   0   1.8T  0 part 
`-sdc2   8:34   0   100M  0 part 
sdd      8:48   0   1.8T  0 disk 
`-sdd2   8:50   0   100M  0 part 
```

sdd 分区出现问题了，没有sdd1 。这个问题不是必然会出现的（这台服务器其他硬盘是正确的，另一台GPU服务器的几个硬盘也是正常的）

docker logs ceph_osd_sdd 输出：
``` shell
+ set -e
+ : ceph
+ :
+ : osd
+ : 0
+ : 0c-c4-7a-82-c5-bc
+ : 0c-c4-7a-82-c5-bc
+ : 0
+ : mds-0c-c4-7a-82-c5-bc
+ : 0
+ : 100
+ : 0
+ : 0
+ : root=default host=0c-c4-7a-82-c5-bc
+ : 0
+ : cephfs
+ : cephfs_data
+ : 8
+ : cephfs_metadata
+ : 8
+ : 0c-c4-7a-82-c5-bc
+ :
+ :
+ : 8080
+ : 0
+ : 9000
+ : 0.0.0.0
+ : cephnfs
+ : 0.0.0.0
+ : 5000
+ : /api/v0.1
+ : warning
+ : /var/log/ceph/ceph-restapi.log
+ : etcd
+ : 127.0.0.1
+ : 4001
+ :
+ :
+ '[' '!' -z '' ']'
+ CEPH_OPTS='--cluster ceph'
+ MOUNT_OPTS='-t xfs -o noatime,inode64'
+ case "$KV_TYPE" in
+ source /config.kv.sh
++ set -e
++ sed -r s/@CLUSTER@/ceph/g /etc/confd/conf.d/ceph.conf.toml.in
++ [[ etcd == \e\t\c\d ]]
++ '[' '!' -z '' ']'
++ CONFD_NODE_SCHEMA=http://
++ echo osd
++ tr '[:upper:]' '[:lower:]'
+ CEPH_DAEMON=osd
+ case "$CEPH_DAEMON" in
+ start_osd
+ get_config
+ CLUSTER_PATH=ceph-config/ceph
+ kviator --kvstore=etcd --client=127.0.0.1:4001 get ceph-config/ceph/monSetupComplete
+ confd -onetime -backend etcd -node http://127.0.0.1:4001 -prefix=/ceph-config/ceph/
2016-10-17T06:01:53Z 0c-c4-7a-82-c5-bc confd[35713]: INFO Backend set to etcd
2016-10-17T06:01:53Z 0c-c4-7a-82-c5-bc confd[35713]: INFO Starting confd
2016-10-17T06:01:53Z 0c-c4-7a-82-c5-bc confd[35713]: INFO Backend nodes set to http://127.0.0.1:4001
+ mkdir -p /var/lib/ceph/bootstrap-osd /var/lib/ceph/bootstrap-mds /var/lib/ceph/bootstrap-rgw
+ echo 'Adding bootstrap keyrings'
+ kviator --kvstore=etcd --client=127.0.0.1:4001 get ceph-config/ceph/bootstrapOsdKeyring
Adding bootstrap keyrings
+ kviator --kvstore=etcd --client=127.0.0.1:4001 get ceph-config/ceph/bootstrapMdsKeyring
+ kviator --kvstore=etcd --client=127.0.0.1:4001 get ceph-config/ceph/bootstrapRgwKeyring
+ check_config
+ [[ ! -e /etc/ceph/ceph.conf ]]
+ create_socket_dir
+ mkdir -p /var/run/ceph
+ chown ceph. /var/run/ceph
+ '[' 0 -eq 1 ']'
+ case "$OSD_TYPE" in
+ osd_trying_to_determine_scenario
+ '[' -z /dev/sdd ']'
++ parted --script /dev/sdd print
++ egrep -sq '^ 1.*ceph data'
Device detected, assuming ceph-disk scenario is desired
Preparing and activating /dev/sdd
+ echo 'Device detected, assuming ceph-disk scenario is desired'
+ echo 'Preparing and activating /dev/sdd'
+ osd_disk
+ osd_disk_prepare
+ [[ -z /dev/sdd ]]
+ '[' '!' -e /var/lib/ceph/bootstrap-osd/ceph.keyring ']'
+ timeout 10 ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring health
2016-10-17 06:01:53.705725 7f8f1787b700  0 -- :/635236832 >> 10.10.14.68:6789/0 pipe(0x7f8f1c05d7a0 sd=3 :0 s=1 pgs=0 cs=0 l=1 c=0x7f8f1c0606c0).fault
HEALTH_OK
+ mkdir -p /var/lib/ceph/osd
+ chown ceph. /var/lib/ceph/osd
++ parted --script /dev/sdd print
++ egrep '^ 1.*ceph data'
+ [[ -n '' ]]
++ parted --script /dev/sdd print
++ egrep '^ 1.*ceph data'
+ [[ -n '' ]]
+ [[ ! -z '' ]]
+ [[ 0 -eq 1 ]]
+ [[ 0 -eq 1 ]]
+ ceph-disk -v prepare --cluster ceph /dev/sdd
command: Running command: /usr/bin/ceph-osd --cluster=ceph --show-config-value=fsid
command: Running command: /usr/bin/ceph-osd --check-allows-journal -i 0 --cluster ceph
command: Running command: /usr/bin/ceph-osd --check-wants-journal -i 0 --cluster ceph
command: Running command: /usr/bin/ceph-osd --check-needs-journal -i 0 --cluster ceph
get_dm_uuid: get_dm_uuid /dev/sdd uuid path is /sys/dev/block/8:48/dm/uuid
set_type: Will colocate journal with data on /dev/sdd
command: Running command: /usr/bin/ceph-osd --cluster=ceph --show-config-value=osd_journal_size
get_dm_uuid: get_dm_uuid /dev/sdd uuid path is /sys/dev/block/8:48/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdd uuid path is /sys/dev/block/8:48/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdd uuid path is /sys/dev/block/8:48/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdd2 uuid path is /sys/dev/block/8:50/dm/uuid
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mkfs_type
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mkfs_options_xfs
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mount_options_xfs
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_fs_mount_options_xfs
get_dm_uuid: get_dm_uuid /dev/sdd uuid path is /sys/dev/block/8:48/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sdd uuid path is /sys/dev/block/8:48/dm/uuid
ptype_tobe_for_name: name = journal
get_dm_uuid: get_dm_uuid /dev/sdd uuid path is /sys/dev/block/8:48/dm/uuid
create_partition: Creating journal partition num 2 size 100 on /dev/sdd
command_check_call: Running command: /sbin/sgdisk --new=2:0:+100M --change-name=2:ceph journal --partition-guid=2:0130d1e5-3f02-4331-979f-0de23dc8843a --typecode=2:45b0969e-9b03-4f30-b4c6-b4b80ceff106 --mbrtogpt -- /dev/sdd
Could not create partition 2 from 206848 to 411647
Error encountered; not saving changes.
Traceback (most recent call last):
  File "/usr/sbin/ceph-disk", line 9, in <module>
    load_entry_point('ceph-disk==1.0.0', 'console_scripts', 'ceph-disk')()
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 4994, in run
    main(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 4945, in main
    args.func(args)
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 1774, in main
    Prepare.factory(args).prepare()
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 1762, in prepare
    self.prepare_locked()
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 1794, in prepare_locked
    self.data.prepare(self.journal)
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 2446, in prepare
    self.prepare_device(*to_prepare_list)
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 2622, in prepare_device
    to_prepare.prepare()
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 1964, in prepare
    self.prepare_device()
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 2054, in prepare_device
    num=num)
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 1522, in create_partition
    self.path,
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 439, in command_check_call
    return subprocess.check_call(arguments)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/sbin/sgdisk', '--new=2:0:+100M', '--change-name=2:ceph journal', '--partition-guid=2:0130d1e5-3f02-4331-979f-0de23dc8843a', '--typecode=2:45b0969e-9b03-4f30-b4c6-b4b80ceff106', '--mbrtogpt', '--', '/dev/sdd']' returned non-zero exit status 4
```

**Comment by typhoonzero** [comment]
Maybe hard to reproduce. I'll check it later.

**Comment by typhoonzero** [comment]
@jiamliang 貌似在 #109 也遇到了同样的问题，当时是怎么解决的呢？

**Comment by jiamliang** [comment]
手动解决的，先执行一下 zap_device ，再重新安装。
上周五使用最新的master分支安装机群的时候，还是会出现分区不正确的情况。
周日将coreos版本从1122.3.0 降到1122.2.0的时候，所有cpu机器的硬盘分区都不正确，GPU的都正确了。
cpu机器只有2个硬盘，一个系统盘，一个数据盘
gpu的机器有4个硬盘，一个系统盘，三个数据盘

**Comment by jiamliang** [comment]
对于多个磁盘都没有进行分区的情况，这个可能和ETCD有关。
如果只分了一个区，这个和etcd就没有关系了。
